baseURL = "https://study.thedegreegap.com/"
languageCode = "en-gb"
title = "The Degree Gap | Tutoring &amp; Study Resources"

[params]
  formspreeEndpoint = "https://formspree.io/f/mvgonabg"
  phone = "+447859965776"
  email = "admin@thedegreegap.com"
  mainSiteURL = "https://thedegreegap.com"

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changeFreq = "monthly"
  priority = 0.6

[permalinks]
  personal-statement-tutor = "/personal-statement-tutor/:contentbasename/"
  personal-statements = "/personal-statements/:contentbasename/"
